"""
Cross-language parity tests.

Replays golden traces generated by the TypeScript engine and verifies
the Python OpenSpiel implementation produces identical results at each step.
"""

import json
import os
from pathlib import Path

import pytest
import pyspiel

import imposter_zero.game as ig

FIXTURES = Path(__file__).parent / "fixtures"


def load_trace(filename):
    with open(FIXTURES / filename) as f:
        return json.load(f)


def make_state_from_trace(trace):
    """Construct an ImposterZeroState with the exact deal from a TS trace."""
    game = pyspiel.load_game("imposter_zero")
    state = game.new_initial_state()

    deck_kinds = ig._regulation_deck(trace["numPlayers"])

    state._card_values = {}
    state._card_names = {}
    for card_id in range(trace["deckSize"]):
        name, value = deck_kinds[card_id]
        state._card_values[card_id] = value
        state._card_names[card_id] = name

    king_base = trace["deckSize"]
    for p in range(trace["numPlayers"]):
        kid = king_base + p
        state._card_values[kid] = 0
        state._card_names[kid] = "King"

    state._hands = [list(h) for h in trace["initialHands"]]
    state._king_face_up = [True] * trace["numPlayers"]
    state._successors = [None] * trace["numPlayers"]
    state._dungeons = [None] * trace["numPlayers"]
    state._court = []
    state._phase = "setup"
    state._active_player = 0
    state._turn_count = 0
    state._accused = trace["accused"]
    state._forgotten = trace["forgotten"]
    state._deck_size = trace["deckSize"]
    state._max_card_id = trace["maxCardId"]
    state._num_players = trace["numPlayers"]

    return state


def trace_fixtures():
    """List all trace fixture files."""
    return sorted(f.name for f in FIXTURES.glob("trace_*.json"))


@pytest.mark.parametrize("fixture", trace_fixtures())
def test_parity_replay(fixture):
    trace = load_trace(fixture)
    state = make_state_from_trace(trace)

    for i, step in enumerate(trace["steps"]):
        assert state.current_player() == step["activePlayer"], (
            f"Step {i}: active player mismatch"
        )
        assert state._phase == step["phase"], (
            f"Step {i}: phase mismatch"
        )

        legal = state.legal_actions()
        assert len(legal) == step["legalActionCount"], (
            f"Step {i}: legal action count mismatch "
            f"(py={len(legal)}, ts={step['legalActionCount']})"
        )

        py_throne = state._throne_value()
        assert py_throne == step["throneValue"], (
            f"Step {i}: throne value mismatch (py={py_throne}, ts={step['throneValue']})"
        )

        assert len(state._court) == step["courtSize"], (
            f"Step {i}: court size mismatch"
        )

        for p in range(trace["numPlayers"]):
            assert len(state._hands[p]) == step["handSizes"][p], (
                f"Step {i}: hand size mismatch for player {p}"
            )

        encoded = step["encodedAction"]
        assert encoded in legal, (
            f"Step {i}: TS-chosen action {encoded} not in Python legal actions {legal}"
        )

        state.apply_action(encoded)

    assert state.is_terminal(), "Expected terminal state after replaying all steps"

    py_returns = state.returns()
    for p in range(trace["numPlayers"]):
        assert py_returns[p] == pytest.approx(trace["terminalReturns"][p]), (
            f"Returns mismatch for player {p}: py={py_returns[p]}, ts={trace['terminalReturns'][p]}"
        )


@pytest.mark.parametrize("fixture", trace_fixtures())
def test_initial_hand_values_match(fixture):
    """Verify that card values in Python match the TS trace card values."""
    trace = load_trace(fixture)
    state = make_state_from_trace(trace)

    for p in range(trace["numPlayers"]):
        py_values = [state._card_values[cid] for cid in state._hands[p]]
        assert py_values == trace["initialHandValues"][p], (
            f"Player {p}: hand value mismatch"
        )

    if trace["accused"] is not None:
        assert state._card_values[trace["accused"]] == trace["accusedValue"]


def test_game_registration():
    """Verify the game registers and produces valid states."""
    game = pyspiel.load_game("imposter_zero")
    assert game.num_players() == 2
    assert game.num_distinct_actions() > 0

    state = game.new_initial_state()
    assert not state.is_terminal()
    assert state.current_player() == 0
    assert len(state.legal_actions()) > 0


def test_random_playout_terminates():
    """A random playout should always terminate."""
    import random
    game = pyspiel.load_game("imposter_zero")

    for seed in range(20):
        rng = random.Random(seed)
        state = game.new_initial_state()
        steps = 0
        while not state.is_terminal() and steps < 200:
            legal = state.legal_actions()
            action = rng.choice(legal)
            state.apply_action(action)
            steps += 1

        assert state.is_terminal(), f"Seed {seed}: did not terminate in {steps} steps"
        assert steps < 200

        r = state.returns()
        assert abs(sum(r)) < 1e-9, f"Seed {seed}: returns don't sum to zero: {r}"
