"""
Cross-language parity tests.

Replays golden traces generated by the TypeScript engine and verifies
the Python OpenSpiel implementation produces identical results at each step.
Covers: crown phase, aligned action codec, firstPlayer, tensors.
"""

import json
from pathlib import Path

import pytest
import pyspiel

import imposter_zero.game as ig

FIXTURES = Path(__file__).parent / "fixtures"


def load_trace(filename):
    with open(FIXTURES / filename) as f:
        return json.load(f)


def make_state_from_trace(trace):
    """Construct an ImposterZeroState with the exact deal from a TS trace."""
    game = pyspiel.load_game("imposter_zero")
    state = game.new_initial_state()

    deck_kinds = ig._regulation_deck(trace["numPlayers"])

    state._card_values = {}
    state._card_names = {}
    for card_id in range(trace["deckSize"]):
        name, value = deck_kinds[card_id]
        state._card_values[card_id] = value
        state._card_names[card_id] = name

    king_base = trace["deckSize"]
    for p in range(trace["numPlayers"]):
        kid = king_base + p
        state._card_values[kid] = 0
        state._card_names[kid] = "King"

    state._hands = [list(h) for h in trace["initialHands"]]
    state._king_face_up = [True] * trace["numPlayers"]
    state._successors = [None] * trace["numPlayers"]
    state._dungeons = [None] * trace["numPlayers"]
    state._court = []
    state._phase = "crown"
    state._active_player = trace["firstPlayer"]
    state._first_player = trace["firstPlayer"]
    state._turn_count = 0
    state._accused = trace["accused"]
    state._forgotten = trace["forgotten"]
    state._deck_size = trace["deckSize"]
    state._max_card_id = trace["maxCardId"]
    state._num_players = trace["numPlayers"]

    return state


def trace_fixtures():
    """List all trace fixture files."""
    return sorted(f.name for f in FIXTURES.glob("trace_*.json"))


@pytest.mark.parametrize("fixture", trace_fixtures())
def test_parity_replay(fixture):
    trace = load_trace(fixture)
    state = make_state_from_trace(trace)

    for i, step in enumerate(trace["steps"]):
        assert state.current_player() == step["activePlayer"], (
            f"Step {i}: active player mismatch"
        )
        assert state._phase == step["phase"], (
            f"Step {i}: phase mismatch (py={state._phase}, ts={step['phase']})"
        )
        assert state._first_player == step["firstPlayer"], (
            f"Step {i}: firstPlayer mismatch (py={state._first_player}, ts={step['firstPlayer']})"
        )

        legal = state.legal_actions()
        assert len(legal) == step["legalActionCount"], (
            f"Step {i}: legal action count mismatch "
            f"(py={len(legal)}, ts={step['legalActionCount']})"
        )

        py_throne = state._throne_value()
        assert py_throne == step["throneValue"], (
            f"Step {i}: throne value mismatch (py={py_throne}, ts={step['throneValue']})"
        )

        assert len(state._court) == step["courtSize"], (
            f"Step {i}: court size mismatch"
        )

        for p in range(trace["numPlayers"]):
            assert len(state._hands[p]) == step["handSizes"][p], (
                f"Step {i}: hand size mismatch for player {p}"
            )

        encoded = step["encodedAction"]
        assert encoded in legal, (
            f"Step {i}: TS-chosen action {encoded} not in Python legal actions {legal}"
        )

        state.apply_action(encoded)

    assert state.is_terminal(), "Expected terminal state after replaying all steps"

    py_returns = state.returns()
    for p in range(trace["numPlayers"]):
        assert py_returns[p] == pytest.approx(trace["terminalReturns"][p]), (
            f"Returns mismatch for player {p}: py={py_returns[p]}, ts={trace['terminalReturns'][p]}"
        )


@pytest.mark.parametrize("fixture", trace_fixtures())
def test_information_state_string_parity(fixture):
    """Verify information state strings match between TS and Python at each step."""
    trace = load_trace(fixture)
    state = make_state_from_trace(trace)

    for i, step in enumerate(trace["steps"]):
        if "informationStateStrings" not in step:
            state.apply_action(step["encodedAction"])
            continue

        for p in range(trace["numPlayers"]):
            py_str = state.information_state_string(p)
            ts_str = step["informationStateStrings"][p]
            assert py_str == ts_str, (
                f"Step {i}, player {p}: info state string mismatch\n"
                f"  py: {py_str}\n"
                f"  ts: {ts_str}"
            )

        state.apply_action(step["encodedAction"])


@pytest.mark.parametrize("fixture", trace_fixtures())
def test_observation_tensor_parity(fixture):
    """Verify observation tensors match between TS and Python at each step."""
    trace = load_trace(fixture)
    state = make_state_from_trace(trace)

    for i, step in enumerate(trace["steps"]):
        if "observationTensors" not in step:
            state.apply_action(step["encodedAction"])
            continue

        for p in range(trace["numPlayers"]):
            py_tensor = state.observation_tensor(p)
            ts_tensor = step["observationTensors"][p]
            assert len(py_tensor) == len(ts_tensor), (
                f"Step {i}, player {p}: tensor length mismatch "
                f"(py={len(py_tensor)}, ts={len(ts_tensor)})"
            )
            for j, (pv, tv) in enumerate(zip(py_tensor, ts_tensor)):
                assert pv == pytest.approx(tv, abs=1e-6), (
                    f"Step {i}, player {p}: tensor[{j}] mismatch (py={pv}, ts={tv})"
                )

        state.apply_action(step["encodedAction"])


@pytest.mark.parametrize("fixture", trace_fixtures())
def test_initial_hand_values_match(fixture):
    """Verify that card values in Python match the TS trace card values."""
    trace = load_trace(fixture)
    state = make_state_from_trace(trace)

    for p in range(trace["numPlayers"]):
        py_values = [state._card_values[cid] for cid in state._hands[p]]
        assert py_values == trace["initialHandValues"][p], (
            f"Player {p}: hand value mismatch"
        )

    if trace["accused"] is not None:
        assert state._card_values[trace["accused"]] == trace["accusedValue"]


def test_game_registration():
    """Verify the game registers and produces valid states."""
    game = pyspiel.load_game("imposter_zero")
    assert game.num_players() == 2
    assert game.num_distinct_actions() > 0

    state = game.new_initial_state()
    assert not state.is_terminal()
    assert state._phase == "crown"
    assert len(state.legal_actions()) == 2


def test_random_playout_terminates():
    """A random playout should always terminate."""
    import random
    game = pyspiel.load_game("imposter_zero")

    for seed in range(20):
        rng = random.Random(seed)
        state = game.new_initial_state()
        steps = 0
        while not state.is_terminal() and steps < 200:
            legal = state.legal_actions()
            action = rng.choice(legal)
            state.apply_action(action)
            steps += 1

        assert state.is_terminal(), f"Seed {seed}: did not terminate in 200 steps"
        assert steps < 200

        r = state.returns()
        assert abs(sum(r)) < 1e-9, f"Seed {seed}: returns don't sum to zero: {r}"


def test_clone_produces_independent_copy():
    """Verify that cloned states are independent."""
    game = pyspiel.load_game("imposter_zero")
    state = game.new_initial_state()

    legal = state.legal_actions()
    action = legal[0]

    cloned = state.clone()
    cloned.apply_action(action)

    assert state._phase == "crown"
    assert cloned._phase == "setup"
    assert state._turn_count == 0
    assert cloned._turn_count == 1


def test_action_codec_round_trip():
    """Verify encode-decode round-trip for all action types."""
    max_card_id = ig._MAX_CARD_ID_2P
    num_players = 2

    decoded = ig._decode_action(ig._DISGRACE_SLOT, max_card_id, num_players)
    assert decoded == ("disgrace",)

    for card_id in range(max_card_id + 1):
        encoded = ig._encode_play(card_id)
        decoded = ig._decode_action(encoded, max_card_id, num_players)
        assert decoded == ("play", card_id), f"play round-trip failed for card {card_id}"

    for s in [0, 5, max_card_id]:
        for d in [0, 5, max_card_id]:
            if s == d:
                continue
            encoded = ig._encode_commit(s, d, max_card_id)
            decoded = ig._decode_action(encoded, max_card_id, num_players)
            assert decoded == ("commit", s, d), f"commit round-trip failed for ({s},{d})"

    for fp in range(num_players):
        encoded = ig._encode_crown_action(fp, max_card_id)
        decoded = ig._decode_action(encoded, max_card_id, num_players)
        assert decoded == ("crown", fp), f"crown round-trip failed for player {fp}"
